name: GenerateSnake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"


jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: preview
          build_dir: dist/img
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
