name: README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-23 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 环境配置
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: 缓存
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: 安装依赖
        run: npm install
      - name: 生成 README.md
        env:
          M3O_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: npm run build --if-present
      - name: 推送新 README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
    
